version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: jobsbolt-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  postgres:
    image: postgres:13
    container_name: jobsbolt-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: jobsbolt-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: jobsbolt-grafana
    ports:
      - "3001:3000" # Grafana is exposed on port 3000 internally, use 3001 for host access to avoid conflicts
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

  # jobsboltapi:
  #   image: coldbolt/jobsbolt-api:dev-latest
  #   container_name: jobsbolt-api
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env # Load application-specific environment variables from .env
  #   depends_on:
  #     - postgres
  #     - rabbitmq
  #     - prometheus

  # jobsboltworker:
  #   image: coldbolt/jobsbolt-worker:latest
  #   container_name: jobsbolt-worker
  #   env_file:
  #     - .env # Load application-specific environment variables from .env
  #   depends_on:
  #     - postgres
  #     - rabbitmq
  #     - prometheus
  #     - jobsboltapi
  
  # psql-tester:
  #   image: alpine
  #   container_name: psql-tester
  #   entrypoint: sh -c "while true; do sleep 3600; done"

volumes:
  grafana-storage: # Persistent storage for Grafana dashboards and setting
