name: Dev envioronment CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Run Stryker
        run: npx stryker run

  dockerBuild:
    runs-on: self-hosted
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches the full Git history

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Branch Name
        id: branch_name
        run: |
          echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build --build-arg SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} -t coldbolt/jobsbolt-api:dev-latest -t coldbolt/jobsbolt-api:${{ env.BRANCH_NAME }}-dev .

      - name: Push Docker Image
        run: |
          docker push coldbolt/jobsbolt-api:dev-latest
          docker push coldbolt/jobsbolt-api:${{ env.BRANCH_NAME }}-dev
