name: Dev envioronment CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      # - name: Run Stryker
      #   run: npx stryker run

  sentry_release:
    needs: test # Ensure this runs after 'test' job is successful
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      # Build and upload sourcemaps in one step by passing SENTRY_AUTH_TOKEN as env
      - name: Build Application with Sourcemaps
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: npm run build

  dockerBuild:
    runs-on: ubuntu-latest
    needs: sentry_release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches the full Git history

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Date for Tag
        id: get_date
        run: |
          DATE_TAG=$(date +'%d%m%Y')
          echo "DATE_TAG=$DATE_TAG" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t coldbolt/jobsbolt-api:main-latest -t coldbolt/jobsbolt-api:${{ env.DATE_TAG }}-main .

      - name: Push Docker Image
        run: |
          docker push coldbolt/jobsbolt-api:main-latest
          docker push coldbolt/jobsbolt-api:${{ env.DATE_TAG }}-main
